#Created by Godfrey P Menezes. Feel free to use, change and share.
#This creates a simpe Pod with nginx image that runs on 80 port.
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-default
spec:
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: IfNotPresent 
    # Option for Always or :latest - https://kubernetes.io/docs/concepts/containers/images/#updating-images
    # Option for IfNotPresent or Never - https://kubernetes.io/docs/concepts/containers/images/#pre-pulled-images
    ports:
    - containerPort: 80
      name: nginx-port
