#Created by Godfrey P Menezes. Feel free to use, change and share.
#This creates a simple Pod with nginx image that runs on 80 port.
#create the configmap cm-literal and then use it in Pod. The command is -
# kubectl create secret generic  secret-val --from-literal=secret-pwd=password --from-literal=secret-user=godfrey
#or the YAML as decribed in here
apiVersion: v1
data:
  secret-pwd: c2VjcmV0LXB3ZA==
  secret-user: c2VjcmV0LXVzZXI=
kind: Secret
metadata:
  name: secret-val
  namespace: default
type: Opaque
---
# The pod will have both the variables in env and it can be checked as kubectl exec nginx-envfrom-secretRef -it -- printenv
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-envfrom-secretref
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - secretRef:
        name: secret-val
    ports:
    - containerPort: 80
      name: nginx-port
