#Created by Godfrey P Menezes. Feel free to use, change and share.
#This creates a simpe Pod with nginx image that runs on 80 port.
#The Quality of Service is Burstable with resources with requests and limits.
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-burstable
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      name: NGINX_PORT
    resources:
      limits:
        cpu: "1"
        memory: 500Mi
      requests:
        cpu: "0.5"
        memory: 100Mi
