#Created by Godfrey P Menezes. Feel free to use, change and share.
#This creates a simpe Pod with nginx image that runs on 80 port assigned to service account test
#The command to create the service account
# kubecctl create sa test
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-sa
spec:
  serviceAccountName: test
  serviceAccount: test
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      name: nginx-port
